---
output:
  pdf_document: default
  html_document: default
---
```{r, include=F}
# Placeholder for clinical evaluation
# = history and physical
# Nutritional evaluation
```
# Discharges

**Discharge Prescriptions**

Prescriptions should be ideally be prepared the day prior to anticipated discharge and left in the patient’s ‘soft chart.’ According to North Carolina STOP guidelines, opioid prescriptions for postoperative patients should be for no more than a 7 day supply.

**Postop Clinic Appts**

Postoperative patients are generally seen for a Transition of Care visit within the first week

Discharge appointments are made by sending a message in Canopy the evening prior (preferred) OR the morning of discharge before 8am to:

- LCI CMC GI, Clerical
- Verona Jordan (Hill) OR Marsha Sukhdeo (Salo and Squires)
- Stefanie Olson (Hill) OR Kendra Zacharias (Salo and Squires)
- Brenda Prieto
- Brnadon Galloway

Please include the following information in the Canopy Message:

- Name of attending
- Ward from which the patient is being discharged
- Desired date for appointment
- Need for Wound Ostomy RN appointment at same time (essential for new stomas)
- Need for bloodwork at first visit
- Other studies to be done after discharge
  - Upper GI
  - Chest X-ray
  - Modified Barium Swallow

If messages cannot be sent in time, clinic schedulers can be reached at: Marsha Sukhdeo (Salo and Squires): 980-442-6110 or Verona Jordan (Hill): 980-442-6183.

If schedulers are not available, clinic RNs can be reached at:  Stefanie Olson (Hill) 980-442-6146 or Kendra Zacharias (Salo and Squires) 980-442-6143.

For patients likely to go home over the weekend or holidays, please plan to send a canopy message before 3pm on Friday or the day prior.

The scheduler will respond with a message to the discharging resident AND to the ward CNL with the appointment time, which can be included within the discharge summary. Copies of the message will also be sent to clinical nurse leaders:

- 11Tower: Sharon Hood
- 6Tower: Amy Peterson

**Additional Appointments**

If followup appointments in additional to surgical followup are needed, these should be designated on the discharge orders. Particularly:

- Primary Care Physician
- Cardiologist (if new cardiac medicines)
- Co-surgeons (Urology, Thoracic Surgery, GYN)

**Discharge Summary**

The discharge summary documents important events and complications in the postoperative course and serves to inform the referring physician and primary physician about these events, but also serves as a blueprint for post-discharge treatment planning. Please recognize that the first post-operative visit may be with a resident who may be meeting the patient for the first time. Key items to include:

|||
|----|-----------------------------------------------------------------|
| N  | Followup plan for chronic pain management                  |
|    | Stroke                                                         |
| CV | Postop Arrhythmia? \| MI? \| CHF?                                          |
|    | If new cardiac meds: Who is managing medications               |
|    | If afib: CHADS score and anticoagulation plan              |
| R  | Pneumonia? \| ARDS? \|  TRACH? |
|    | Need for home oxygen?                                          |
|    | CXR needed at first postop visit?                                                  |
|GI	|Delayed gastric emptying? \| leak? \| ileus?|
|    |Tube feed regimen|
|     |Diet at discharge (Low residue \| Full liquds \| Meds with thickened water \|NPO)|
|   |New stoma (ileostomy \| colostomy)|
|     |Wound care needs (VAc \| Prevena)
|GU	|Urinary Retention|
|  |Discharge with foley catheter|
|H	|Complications: DVT \| PE|
|   |Anticoagulation Plan|
|Endo|Insulin regimen at DC (dose will be in med rec)|
|ID|Antibiotics at DC|
||Return to ICU|


**Communication**

It is essential that discharge summaries be sent to the patient’s primary MD and referring physician. Please review the initial consultation note for the names of providers involved in a patient’s care.

In order to easily access the patient’s providers, please prepare a “]Providers” autotext:

Click the AutoText icon on a document
Add new AutoText by clicking the blue + sign
Create a name for the new AutoText (such as “]Providers”)
Select a smart template by clicking the second icon from the right of the buttons
Search for “Transition” and select “Transition Clinic Header”
Save the AutoText
Please paste the ]Providers AutoText in the body of the discharge summary to easily access who should receive copies of the discharge summary
