---
output:
  html_document: default
  pdf_document: default
---
```{r, include=F}
# Placeholder for clinical evaluation
# = history and physical
# Nutritional evaluation
```
# Esophagectomy Postop

**ICU Care**

All patients admitted to STICU with Surgical Critical Care Consultation. Surgical critical care will need a phone call immediately after surgery at 6-0366. Listed: Dr Salo, CMC-GI Surgical Oncology, CMC-Surgical Critical Care. Diabetic patients (on insulin preop): Consult Kelli Dunn.

**Ward Care**

Once stable, patients are transferred to 6T. If a 6T bed is not available, please notify Dr Salo. Historically, over 95% of patients are transferred to 6T after leaving the ICU.

**Neuro**

Multimodal pain control:

- gabapentin (300mg tid liquid via Jejunostomy)
- Tylenol (1000mg q6hrs as pediatric liquid via Jejunostomy).
- PCA with subsequent conversion to oxycodone elixir via Jejunostomy.
- No ketorolac (Toradol) given risk of anastomotic failure​1​
- Home anxiolytics are generally administered at half the home dose

**Cardiovascular**

Postoperative atrial fibrillation is a common occurrence (20%) after esophagectomy, with the risk increasing in older patients. For patients over age 70, half of patients will develop atrial fibrillation in the postoperative period.

For prevention of atrial fibrillation, beta blockade is used. For patients receiving beta blockers prior to surgery, continuation of beta blockade is recommended. For others, patients are given metoprolol 2.5 mg IV q6hrs which can be titrated up to 10mg IV q6hrs as needed. See STS Guidelines.​2​

Home anti-hypertensives are usually held in order to allow beta-blockade. Patients who have elevated blood pressures once they are adequately beta-blocked (eg HR 60-70) are usually restarted on their home anti-hypertensives. *Home anti-hypertensives are not routinely restarted postoperatively*

**Respiratory**

Chest tubes generally consist of a 28Fr Blake drain placed into the right chest. This is placed to water seal when output is less than 200mL/day and there is no leak visible in the Pleurevac container. Chest tubes are usually removed once output is less than 150mL/day and drainage is clear without evidence of chyle (milky appearance). A chest x-ray is obtained after removing a chest tube to look for a pneumothorax.

**Gastrointestinal**
All patients receive pantoprazole 40mg IV daily and metoclopramide 5-10mg IV q 6hrs

**Nutrition**

All esophagectomy patients receive a feeding jejunostomy at the time of operation. In the immediate post-operative period, patients receive Osmolite 1.5 starting the day of surgery once they are off pressors. Tube feeds are started at 20mL/hour until flatus and then advanced at 10mL per hour every 8 hours, up to a goal of 60mL per hour (x24 hours). Patients who are on tube feeds prior to surgery are generally restarted on their home tube feed formula.

Patients who do not tolerate Osmolite are switched to Vital 1.5, which is pre-hydrolyzed. In order to allow enough time for switching of tube feedings, patients are generally switched from Vital to their home tube feeding formula 3-4 days prior to discharge. This is typically done when they are transferred out of the ICU.

Obese patients (BMI>30) are started on Promote at 20mL/hour and increased to a goal of 60mL/hour. Promote contains a more protein relative to carbohydrdates. An alternative is Vital High Protein, which is similar to Promote but using hydrolyzed proteins.

Diarrhea in patients on tube feeds (especially nocturnal diarrhea) needs to be addressed. Despite STICU guidelines for nutrition in trauma patients, diarrhea (especially night-time diarrhea) is justification for alteration in tube feeds. See Diarrhea and Jejunstomy Feeding

*Diabetic Patients*

Patients who require EndoTool in the ICU will need an endocrinology consult. See also [Jejunostomy Feedings with Diabetes](#jejunostomy_diabetes)


*‘Free Water’*

In addition to tube feeds, most patients will receive ‘free’ water flushes through the jejunostomy. This is typically done as 240mL four times per day (for a total of 32oz)

*Nasogastric Tubes*

A silicone nasogastric tube (Covidien Salem Sump) is placed in all patients during surgery and the position confirmed by ultrasound intraoperatively. Tubes are positioned so that all 4 dots are outside.  Gastric emptying is evaluated with upper GI prior to NG tube removal. Once extubated, upper GI is typically performed on the 2nd through 4th postoperative day. Conversely, patients who are intubated will keep their nasogastric tube until extubated. Radiology ordered as "upper GI Series". In the comments section please add "IsoVue through NG tube. Halo Dr Salo for study". See Evaluation of GI Function

*Drains*

- JP1: 19Fr Blake drain in left pleura. The exit site the most lateral drain and is secured with a blue suture
- JP2: 19Fr Blake drain in right pleura. The exit site is medial to JP1 and is secured with a black suture
- JP3: 19 Fr Blake drain in abdomen.  If used, the exit site is most medial and is secured with a blue suture
- JP4: 15Fr Blake drain in neck (for cervial incision)
- JP5: 15Fr Blake drain in subcutaneous tissue of incision

*Evaluation for Anastomotic leak*

[Drain amylase](#drain_amylase) is an inexpensive, specific, and relatively sensitive test for anastomotic leak. Fluid from JP2 (right chest) is sent for “Body Fluid Amylase” starting on postoperative day #4 and continued until postoperative day 9. Drain amylase over 400IU/ml is considered positive and prompts a [CT esophagram](#ct_esophagram) for confirmation. See also [Evaluation for Anastomotic Leak](#leak_evaluation)

**Renal**
Total fluids (IV + tube feeds) are generally run at 75mL/hour. Foley catheter is removed on the first or second day after surgery. Some patients will need diuresis on the 3rd or 4th postoperative day

**Heme**
All patients require VTE prophylaxis with Lovenox or heparin SQ.

Preoperative anti-platelet agents are started on the first (aspirin) or second (Plavix) postoperative day if there is no excessive bleeding from the chest tube or JP drains.  Patients on preoperative anticoagulation are transitioned to therapeutic Lovenox on the second postoperative day if no signs of bleeding.

**ID**
Prophylactic Cefazolin and Flagyl are administered for 24 hours and stopped


