# Locally-Advanced Gastric

Locally-advanced gastric cancer (T3 or N^+^) is generally treated with some form of adjuvant therapy, which has been shown to improve upon the outcomes with surgery alone.

## Preoperative Chemotherapy

FLOT chemotherapy [@al-batran1948]

MAGIC study randomized 503 patients to perioperative 'sandwich' therapy consisting of epirubicin, cisplatin, and 5-FU versus surgery alone.  In the perioperative chemotherapy group, 4 cycles were administered prior to surgery, and 4 cycles afterwards. Tumors of the esophagus or gastroesophageal junction comprised 26% of the study population. While over 90% of patients assigned to the chemotherapy arm completed their preoperative chemotherapy, only 66% completed their postoperative therapy.  Survival at 5 years was 36% in the perioperative chemotherapy group, compared with 24% in the surgery group (p<0.001).[@cunningham11]

CLASSIC clinical trial randomized 1033 patients with stage II or III gastric cancer after D2 gastrectomy to 6 months of adjuvant chemotherapy versus surgery alone. Three-year survival was improved in the chemotherapy group (74% *v* 59%).[@bang315]

The FFCD trial randomized patients to preoperative chemotherapy with 2 or 3 yccles of cisplatin and 5-FU versus surgery alone. Tumors of the lower esophagus or gastroesophageal junction comprised 75% of the study population. Survival at 5 years was longer in the chemotherapy group (38%) versus 24% in the surgery alone group (p=0.02).[@ychou1715]

## Postoperative chemotherapy

CLAASIC trial [@noh1389]  [@bang315] patients with II or IIIB gastric cancer received gastrectomy with D2 node dissection randomized to postoperative chemotherapy with capecitabine and oxaliplatin. Chemotherapy group had improved 3-year DFS (74% vs 59% P<.0001)


## Postoperative chemoradiation

Intergroup 0116 trial [@macdonald725]
Surgical quality control was poor, as 90% were treated a limited lymph node dissection. Long-term followup, however [@smalley2327] showed a persistent benefit of postoperative chemoradiation.


ARTIST trial 450 patients treated with a D1 $\alpha$ gastrectomy  were randomized to adjuvant capcitibine and cisplatin versus chemoradiation consisting of two cycles of capcitabine/oxalipaltin followed by chemoradiation followed by chemotherapy. Overall 3- year survival did differ between groups (78.2% vs 74.2% p =0.86). A post-hoc analysis of patients with positive nodes showed a beneficial effect of chemoradiation (77.5% *v* 72.3% p=0.365).[@lee268]

CRITICS trial treated all patients with preoperative chemoterhapy followed by surgery.  Postoperative patients were then randomized between additional chemotherapy versus chemoradiation.



## Preoperative chemoradiation

[@ajani3953]
